johnny/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include ('tienda.urls')),
    path('accounts/' , include ('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path, include
from . import views
from .views import home , registro, ProductoViewset
from rest_framework import routers

router = routers.DefaultRouter()
router.register('producto', ProductoViewset)

urlpatterns = [
    path('', home, name='home'),
    path('', views.home, name='index'),
    path('agregar-producto', views.agregar_producto, name='agregar-producto'),
    path('listar-producto', views.listar_producto, name='listar-producto'),
    path('modificar-producto/<id>', views.modificar_producto, name='modificar-producto'),
    path('eliminar-producto/<id>', views.eliminar_producto, name='eliminar-producto'),
    path('registro/', registro, name="registro"),
    path('api/', include(router.urls)),
]

tienda/models.py
from django.db import models

# Create your models here.


class Marca(models.Model):
    nombre = models.CharField(max_length=70)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=70)
    precio = models.IntegerField()
    sabor = models.CharField(max_length=60)
    peso = models.CharField(max_length=8)
    imagen = models.ImageField(upload_to = "productos", null=True)
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)

def __str__(self):
        return self.nombre

tienda/forms.py
from django import forms
from .models import Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ValidationError


class ProductoForm(forms.ModelForm):

    nombre = forms.CharField(min_length=3 , max_length=50)
    precio = forms.IntegerField(min_value=1, max_value=30000)

    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]
        existe = Producto.objects.filter(nombre__iexact=nombre).exists()

        if existe:
            raise ValidationError("Este Nombre Ya Existe")

        return nombre

    class Meta:
        model = Producto
        fields = "__all__"

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username', "first_name", "last_name", "email", "password2"]

tienda/views.py
from django.shortcuts import render , redirect, get_object_or_404
from .models import Producto
from .forms import ProductoForm, CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
from rest_framework import viewsets
from .serializers import ProductoSerializer
# Create your views here.


class ProductoViewset(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer


def home(request):

    productos = Producto.objects.all()
    data = {"productos": productos}
    return render(request, 'tienda/index.html', data)

@permission_required('tienda.agregar_producto')
def agregar_producto(request):
    data = {'form': ProductoForm()}

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "GUARDADO CORRECTAMENTE"
        else:
            data['form'] = formulario

    return render(request, 'tienda/producto/agregar.html', data)
@permission_required('tienda.listar_producto')
def listar_producto(request):
    productos = Producto.objects.all()
    data = {"productos": productos}
    return render(request, 'tienda/producto/listar.html', data)
@permission_required('tienda.modificar_producto')
def modificar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    data = {'form' : ProductoForm(instance=producto)}

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "Producto Modificado Correctamente"
            return redirect(to="listar-producto")
            data['form'] = formulario
    return render(request, 'tienda/producto/modificar.html', data)
@permission_required('tienda.eliminar_producto')
def eliminar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    return redirect(to="listar-producto")


def registro(request):
    data = {
        'form': CustomUserCreationForm
        }

    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            #redirigir al home
            return redirect(to="home")
        data["form"] = formulario
    return render(request, 'registration/registro.html', data)

tienda/templates/tienda/Index.html
{% extends 'tienda/base.html' %}
{% block contenido %}
{% load humanize %}
{% load static %}
      <!-- Broaster Burgers -->
<section>
<div class="row pt-5 pb-5 m-0">
  {% for p in productos %}
  <div class="col-md-3">
    <div class="card mb-3">
      {% if p.imagen %}
      <img src=" {{p.imagen.url}}" class="card-img-top" alt="...">
      {% endif %}
      <div class="card-body text-center">
        <h5 class="card-title fs-2 fw-bold">{{p.nombre}}</h5>
        <p class="card-text fs-5 fw-bold">${{p.precio | intcomma}}</p>
        <p class="card-text fs-5 fw-bold">{{p.sabor}}</p>
        <p class="card-text fs-5 fw-bold">{{p.peso}}</p>
        <p class="card-text fs-5 fw-bold">{{p.marca }}</p>
        <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          Comprar
        </button>
      </div>
    </div>

  </div>
  {% endfor %}











{% endblock %}

tienda/templates/tienda/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Utilizamos un icono para la pagina: -->
  <link rel="icon" href="./Images/Logo-black.png">
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Importamos bootstrap v5.0.2 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- Importamos nuestro CSS local -->
  <link rel="stylesheet" href="CSS/home.css">
  <link rel="stylesheet" href="CSS/global.css">
  <link rel="stylesheet" href="{% static 'tienda/CSS/style.css' %}">
  <!-- Importamos iconos para html basicos de font-awesome 4.7.0: -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Importamos google fonts: -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap" rel="stylesheet">
  <title>Johnny Roster</title>
</head>
<body>
  <section class="homeStyle">
    <div>
      <!-- NavBar -->
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">
            <a href="Index.html"><img src="{% static 'tienda/Images/Logo-black.png' %}" alt="logotipo" width="60px" height="50px"></a>
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">


              <!-- PRINCIPAL -->
              <li class="nav-item">
                <a class="nav-link active" text-white aria-current="page" href="{% url 'home' %}">Principal<i class="fa fa-fw fa-home"></i></a>
              </li>
              <!-- PRINCIPAL -->

              <!-- Contacto -->
              <li class="nav-item">
                <a class="nav-link text-white"  href="{% url 'listar-producto' %}">Ver productos<i class="fa fa-fw fa-envelope" aria-hidden="true"></i></a>
              </li>
              <!-- Contacto -->

              <!-- MENU -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="menu.html" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                  aria-expanded="false">Menu<i class="fa fa-fw fa-cutlery" aria-hidden="true"></i>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="tercio-de-libra.html">Broaster</a></li>
                  <li><a class="dropdown-item" href="onion-bacon.html">100% Carne</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li>
                    <a class="dropdown-item" href="menu.html">Acompañamientos</a>
                  </li>
                </ul>
              </li>
              <!-- MENU -->


              <!-- CARRITO -->

              {% if perms.app.add_producto %}
              <li class="nav-item">
                <a class="nav-link  text-white" href="{% url 'agregar-producto' %}" tabindex="-1" aria-disabled="true"> Agregar Producto<i class="fa fa-fw fa-shopping-cart" aria-hidden="true"></i></a>
              </li>
              {% endif %}
              {% if perms.app.view_producto %}
              <!-- CARRITO -->
              {% endif%}
              {% if user.is_authenticated %}

              <li>
                <a href="{% url 'logout' %}" class="btn btn-danger float-sm-end">Cerrar Sesion</a>
              </li>

              {% else %}
              <li>
                <a href="{% url 'login' %}" class="btn btn-warning float-lg-end">Iniciar Sesion</a>
              </li>
              {% endif %}
              <li>
                <a href="{% url 'registro' %}" class="btn btn-light ">Registrate</a>
              </li>

              <!-- AGREGAR -->
            </ul>
            
          </div>
        </div>
      </nav>
      <!-- Nav bar antiguo -->
      <!-- <div class="navbar navbar-fixed-top">
                <a class="active2" href="Index.html">
                    <p><i class="fa fa-fw fa-home"></i>Principal</p>
                </a>
                <a href="menu.html">
                    <p><i class="fa fa-fw fa-cutlery" aria-hidden="true"></i> Menu</p>
                </a>
                <a
                    href="https://api.whatsapp.com/send/?phone=56963865863&text=Hola+amigos%21+%EF%BF%BD&type=phone_number&app_absent=0">
                    <p><i class="fa fa-fw fa-whatsapp" aria-hidden="true"></i> Contacto</p>
                </a>
                <a href="https://www.pedidosya.cl/restaurantes/vina-del-mar/johnny-roster-menu">
                    <p><i class="fa fa-fw fa-shopping-cart" aria-hidden="true"></i> Carrito</p>
                </a>
            </div> -->


            <!-- Header -->
      <div class="titulo ">
        <h1 class="texto-banner fw-bold text-dark">JOHNNY ROSTER</h1>
      </div>
      <br>
      <br>
      <!-- Header -->


      <!-- CARRUSEL 
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active ">
            <img src="./Images/a1.jpg" class="d-block w-100" alt="a1">
            <div class="carousel-caption ">
              <h5 class="fw-bold fs-1 letras_carrusel">LAS MEJORES HAMBURGUESAS</h5>
              
            </div>
          </div>
          <div class="carousel-item ">
            <img src="./Images/a2.png " class= "d-block w-100" alt="a2">
            <div class="carousel-caption ">
              <h5 class="fw-bold fs-1 letras_carrusel">LAS MEJORES PAPAS FRITAS</h5>
              
            </div>
          </div>
          <div class="carousel-item ">
            <img src="./Images/a3.jpg" class="d-block w-100" alt="a3">
            <div class="carousel-caption ">
              <h5 class="fw-bold fs-1 letras_carrusel">LOS MEJORES POLLOS</h5>
              
            </div>
          </div>
        </div>
      </div>
      
    -->


      <!-- EX Carrusel -->
      
      <div id="carrusel ">
        <div id="demo" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-indicators ">
            <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
          </div>

          <div class="carousel-inner">


            <div class="carousel-item active ">
              <img src="{% static 'tienda/Images/1366_2000.jpg' %}" alt="Los Angeles" class="carrouselimg d-block" style="width:100%">
              <div class="carousel-caption">
                <h3 class="fw-bold fs-2 letras_carrusel">Las buenas burgers están acá</h3>
              </div>
            </div>


            <div class="carousel-item  ">
              <img src="{% static 'tienda/Images/Tipos-de-hamburguesas.jpg' %}" alt="Chicago" class="carrouselimg d-block"
                style="width:100%">
              <div class="carousel-caption">
                <h3 class="fw-bold fs-2 letras_carrusel">Opciones vegetarianas</h3>
              </div>
            </div>



            <div class="carousel-item ">
              <img src="{% static 'tienda/Images/hamburguesas.jpg' %}" alt="New York" class="carrouselimg d-block" style="width:100%">
              <div class="carousel-caption">
                <h3 class="fw-bold fs-2 letras_carrusel">Para toda la familia</h3>
              </div>
            </div>

            

          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
          </button>
        </div>
      </div>
    

<div class="row m-0">
  <div class="col-12">
    <h1 class="text-center  text-black fw-bold pt-5 hamburguesa">BURGUES PREMIUM</h1>
  </div>
</div>


{% block contenido %}

{% endblock %}




    <!-- Footer -->
    <footer class="bg-dark text-center text-white">
      <!-- Grid container -->
      <div class="container p-1">
        <!-- Section: Social media -->
        <section class="mb-2">
          <!-- Facebook -->
          <a class="btn btn-outline-light rounded-circle btn-floating m-1"
            href="https://www.facebook.com/profile.php?id=100063007042413" target="_blank" role="button"><i
              class="fa fa-facebook-official"></i></a>
          <!-- Instagram -->
          <a class="btn btn-outline-light rounded-circle btn-floating m-1"
            href="https://www.instagram.com/johnnyroster3/?hl=es" target="_blank" role="button"><i
              class="fa fa-instagram"></i></a>
          <!-- Whatsapp -->
          <a class="btn btn-outline-light rounded-circle btn-floating m-1"
            href="https://api.whatsapp.com/send/?phone=56963865863&text=Hola+amigos%21+%EF%BF%BD&type=phone_number&app_absent=0"
            target="_blank" role="button"><i class="fa fa-whatsapp"></i></a>
          <!-- Github -->
          <a class="btn btn-outline-light rounded-circle btn-floating m-1"
            href="https://github.com/jlchnb/Johnny-Roster" target="_blank" role="button"><i
              class="fa fa-github"></i></a>
        </section>
        <section class="d-flex justify-content-evenly">
          <div>
            <img src="{% static 'tienda/Images/Logo-black.png' %}" width="150" height="140">
            
          </div>
        </section>

      </div>
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2023 Copyright:
        <a class="text-white" href="index.html">Johnny-Roster</a>
      </div>
    </footer>
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel"></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Se a agregado exitosamente
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrrar</button>
        <button type="button" class="btn btn-primary">Ir Al Carro De Compra</button>
      </div>
    </div>
  </div>
</div>





    </div>
  </section>




  <!-- Scripts para que el carrusel funcione -->
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"
    integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>
</body>

</html>

tienda/templates/tienda/producto/agregar.html
{% extends 'tienda/base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters%}
{% block contenido %}

<section class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-12 cold-md-6">
            <div class="card">
                <div class="card-body">
                    {{mensaje}}

    <form action="" method="post" enctype="multipart/form-data">


        {% csrf_token %}
        {{ form | crispy}}

        <div class="d-flex justify-content-evenly">
            <input type="submit" value="GUARDAR" class="btn btn-primary">
            <input type="submit" value="CANCELAR" class="btn btn-secondary">

        </div>
        
    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

tienda/templates/tienda/producto/listar.html
{% extends 'tienda/base.html' %}
{% load humanize %}
{% block contenido %}

<section class="container">
    <div class="table-hover table-responsive mt-5">
        <table class="table table-striped">
            <tr>
                <th>Nombre</th>
                <th>Marca</th>
                <th>Precio</th>
                <th>Sabor</th>
                <th>Peso</th>
                <th>Imagen</th>
                <th></th>
                <th>Opciones</th>
            </tr>
            {% for p in productos%}
            <tr>
                <td>{{p.nombre}}</td>
                <td>{{p.marca}}</td>
                <td>{{p.precio | intcomma }}</td>
                <td>{{p.sabor}}</td>
                <td>{{p.peso}}</td>
                {% if p.imagen %}
                <td><img src="{{ p.imagen.url }}" alt="imagen-producto" class="w-25"></td>
                {% endif %}

                {% if perms.app.change_producto %}
                <td><a href="{% url 'modificar-producto' p.id %}" class="btn btn-warning">Modificar</a></td>
                {% endif %}
                {% if perms.app.delete_producto %}
                <td><a href="{% url 'eliminar-producto' p.id %}"class="btn btn-danger">Eliminar</a></td>
                {% endif %}
            </tr>

            {% endfor %}
        </table>
</div>
</section>





{% endblock %}

tienda/templates/tienda/producto/modificar.html
{% extends 'tienda/base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters%}
{% block contenido %}

<section class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-12 cold-md-6">
            <div class="card">
                <div class="card-body">
                    {{mensaje}}

    <form action="" method="post" endtype="multipart/form-data">


        {% csrf_token %}
        {{ form | crispy}}

        <div class="d-flex justify-content-evenly">
            <input type="submit" value="GUARDAR" class="btn btn-primary">
            <input type="submit" value="CANCELAR" class="btn btn-secondary">

        </div>
        
    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}